### ISSUE TITLE
User->create() argument checking

### ISSUE THREAD

**Issue by spficklin** [tripal/GalaxyLib-PHP#4]
Galaxy has specific rules for creating users.  The name must be lowercase, etc.  Should we add checks in the User>create() function to keep the user from providing bad argument values or do we get a good enough error from Galaxy to just return a FALSE and let the Galaxy error message inform the user?

**Comment by cwytko** [comment]
I'll see to that our function catches that and doesn't allow the user to invoke the api until the requirements are met that galaxy requires

**Comment by spficklin** [comment]
So after looking into it a bit it seems Galaxy is providing a proper error which can be retrevied by the user using the ->getError() function, so no need to add parameter checking.
