### ISSUE TITLE
Libraries delete isn't working

### ISSUE THREAD

**Issue by spficklin** [tripal/GalaxyLib-PHP#6]
The Libraries::delete function properly marks a library as delete, but it's "undelete" property doesn't seem to work.  

Also, the 'deleted' argument for the Libraries::index() function doesn't seem to work.  It is supposed to filter what gets returned by either deleted or not, but it always returns all libraries.

I suspect this may be an issue with the Galaxy API, but it needs checking.

**Comment by spficklin** [comment]
BTW... I commented out the test for those non-working arguments in the LibrariesTest unit test.

**Comment by cwytko** [comment]
Within the unit testing of the this issue, there are some weird test cases set up (#3 and #4) we'll get back to them later.

**Comment by martenson** [comment]
the Galaxy API should be fine, on current `dev` the request to undelete is as follows

```
{{url}}/api/libraries/a39c9b7b38c0c268?key={{key}}&undelete=true
```
